# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionInfo',
            fields=[
                ('sid', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('vid_1', models.BooleanField(default=False)),
                ('read_1', models.BooleanField(default=False)),
                ('quiz_1', models.BooleanField(default=False)),
                ('quiz_1_passed', models.BooleanField(default=False)),
                ('vid_2', models.BooleanField(default=False)),
                ('read_2', models.BooleanField(default=False)),
                ('quiz_2', models.BooleanField(default=False)),
                ('answers', models.CharField(max_length=256)),
            ],
        ),
    ]
