# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioninfo',
            name='quiz_2_passed',
            field=models.BooleanField(default=False),
        ),
    ]
